"""Tests for the polychromatic (white-beam Laue) period extraction.

Covers §4 of SPEC_polychromatic_period_implementation.md as revised by
ADDENDUM_pixel_space_migration.md.  Every reference value was re-derived
numerically before being frozen here, and the detector projection is checked
against the installed LaueTools rather than against a re-derivation.

Run with:  pytest satellite_peak_analysis/tests/test_laue_period.py -v
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np
import pytest


from laue.satellite.geometry import BEAM_X_TO_Y, B_matrix_hexagonal, DetectorGeometry, G_magnitude, LAB_KI, angular_separation, assert_no_branch_crossing, assert_ub_material, build_canonical_frame, diagnose_ub_frame, dihedral_phi, direction_to_2theta_chi, direction_to_pixel, gamma_from_hkl, gamma_from_vectors, kf_hat, lab_vectors_from_UB, pixel_to_angle, pixel_to_direction, pixels_to_2theta_chi, predict_angular_separations, predict_satellite_angles, predict_satellite_pixels, predicted_satellite_axis_deg, psi_from_geometry, theta_from_G, train_direction_delta_deg, two_theta_chi_to_direction, two_theta_from_direction, ub_from_beam_x_frame
from laue.satellite.period import check_order_assignment, compare_methods, layer_period_from_peaks, locate_sl0_from_ladder, resolve_and_apply_order_sign, resolve_order_sign

try:
    from LaueTools.LaueGeometry import calc_uflab, calc_xycam
    HAS_LAUETOOLS = True
except ImportError:
    HAS_LAUETOOLS = False


# ── Fixtures: GaN (105), µLED calibration from the addendum ──────────────────

GAN_A, GAN_C = 3.189, 5.185
LAM = 0.727
HKL = (1, 0, 5)
LAMBDA_TRUE = 97.0

DET_KW = dict(dd=69.984, xcen=1079.57, ycen=983.73,
              xbet=0.173, xgam=0.382, pixelsize=0.075)
GEOM = DetectorGeometry(**DET_KW, framedim=(2162, 2068))

BOXSIZE = 60


# ── Rotation helpers, for building synthetic orientations ────────────────────

def _rodrigues(axis, angle_rad):
    axis = np.asarray(axis, dtype=float)
    axis = axis / np.linalg.norm(axis)
    K = np.array([[0.0, -axis[2], axis[1]],
                  [axis[2], 0.0, -axis[0]],
                  [-axis[1], axis[0], 0.0]])
    return np.eye(3) + math.sin(angle_rad) * K + (1 - math.cos(angle_rad)) * (K @ K)


def _rot_between(v1, v2):
    """Minimal rotation taking unit v1 onto unit v2."""
    v1 = np.asarray(v1, float) / np.linalg.norm(v1)
    v2 = np.asarray(v2, float) / np.linalg.norm(v2)
    axis = np.cross(v1, v2)
    n = np.linalg.norm(axis)
    if n < 1e-14:
        return np.eye(3) if v1 @ v2 > 0 else -np.eye(3)
    return _rodrigues(axis, math.acos(np.clip(v1 @ v2, -1.0, 1.0)))


def _make_UB(spin_deg: float, azimuth_deg: float = 75.0):
    """A physically consistent UB for the (105) parent reflection at λ = 0.727 Å.

    The plane normal is placed at the Bragg angle to the beam, û·Ĝ = −sin θ, so
    the resulting spot sits at 2θ = 2·arcsin(|G|λ/4π) by construction and the
    pixel position is an OUTPUT.  Placing the spot at an arbitrary pixel instead
    would silently imply a different wavelength — in Laue the spot position is
    fixed by the direction of Ĝ, and λ adjusts to satisfy Bragg.

    ``azimuth_deg`` rotates Ĝ about the beam (moving the spot across the frame);
    ``spin_deg`` rotates the crystal about Ĝ, leaving the parent spot fixed.  The
    latter is the residual freedom the parent spec swept as φ, and varying it is
    what catches convention inversions.
    """
    theta = theta_from_G(G_magnitude(*HKL, GAN_A, GAN_C), LAM)
    a = math.radians(azimuth_deg)
    G_dir = np.array([math.cos(theta) * math.cos(a),
                      -math.sin(theta),
                      math.cos(theta) * math.sin(a)])

    B = B_matrix_hexagonal(GAN_A, GAN_C)
    G_crystal = B @ np.array(HKL, dtype=float)
    G_crystal_hat = G_crystal / np.linalg.norm(G_crystal)

    return _rodrigues(G_dir, math.radians(spin_deg)) @ _rot_between(G_crystal_hat, G_dir)


def _peak(order, pos_along_axis, position_2d=None):
    p = {'order': order, 'pos_along_axis': pos_along_axis,
         'amplitude': 100.0, 'fwhm': 4.0, 'sigma': 1.7}
    if position_2d is not None:
        p['position_2d'] = position_2d
    return p


def _synthetic_pixel_peaks(period_angstrom, UB, orders=range(-3, 4)):
    """Peaks generated by the exact pixel-space forward model, in crop coordinates."""
    orders = list(orders)
    G_lab, z_lab = lab_vectors_from_UB(HKL, (GAN_A, GAN_C), UB)
    col, row = predict_satellite_pixels(G_lab, z_lab, period_angstrom, orders, GEOM)
    col, row = np.asarray(col), np.asarray(row)

    # The crop is centred on the parent spot, whose position is an output of the
    # model — not a value chosen in advance (see _make_UB).
    parent_col, parent_row = direction_to_pixel(kf_hat(G_lab, LAB_KI), GEOM)
    row0, col0 = parent_row - BOXSIZE, parent_col - BOXSIZE
    axis = np.array([col[-1] - col[0], row[-1] - row[0]])
    axis = axis / np.linalg.norm(axis)
    zero = orders.index(0) if 0 in orders else 0

    peaks = []
    for n, cc, rr in zip(orders, col, row):
        s = float(np.array([cc - col[zero], rr - row[zero]]) @ axis)
        peaks.append(_peak(n, s, position_2d=(rr - row0, cc - col0)))
    return peaks, (row0, col0)


# ── §4.1 — γ from indexing ───────────────────────────────────────────────────

@pytest.mark.parametrize('hkl, expected_deg', [
    ((0, 0, 2),  0.0000),
    ((1, 0, 5), 20.5804),
    ((1, 0, 4), 25.1434),
    ((1, 0, 3), 32.0387),
    ((1, 0, 2), 43.1894),
    ((1, 1, 4), 39.1094),
])
def test_gamma_from_hkl_reference_values(hkl, expected_deg):
    got = math.degrees(gamma_from_hkl(*hkl, GAN_A, GAN_C))
    assert got == pytest.approx(expected_deg, abs=0.01)


def test_gamma_symmetric_reflection_is_exactly_zero():
    assert gamma_from_hkl(0, 0, 2, GAN_A, GAN_C) == 0.0


# ── §4.2 — |G| and θ consistency ─────────────────────────────────────────────

def test_G_magnitude_and_theta_consistency():
    G_mag = G_magnitude(*HKL, GAN_A, GAN_C)
    assert G_mag == pytest.approx(6.47205, rel=1e-5)

    theta = theta_from_G(G_mag, LAM)
    G_from_theta = 4.0 * math.pi * math.sin(theta) / LAM
    assert G_from_theta == pytest.approx(G_mag, rel=1e-9)

    assert 2.0 * math.pi / G_mag == pytest.approx(0.97082, abs=1e-5)
    assert math.degrees(theta) == pytest.approx(21.9889, abs=1e-3)


def test_theta_from_G_rejects_inaccessible_reflection():
    with pytest.raises(ValueError, match='outside'):
        theta_from_G(6.47205, 10.0)


# ── §3.1 — B matrix and UB composition (NEW) ─────────────────────────────────

def test_B_matrix_and_UB_composition():
    B = B_matrix_hexagonal(GAN_A, GAN_C)
    hkl = np.array(HKL, dtype=float)
    G_crystal = B @ hkl

    assert np.linalg.norm(G_crystal) == pytest.approx(6.47205, rel=1e-5)
    assert G_crystal[0] == pytest.approx(2.27507, rel=1e-5)
    assert G_crystal[1] == pytest.approx(0.0, abs=1e-12)
    assert G_crystal[2] == pytest.approx(6.05900, rel=1e-5)

    gamma_crystal = gamma_from_vectors(G_crystal, np.array([0.0, 0.0, 1.0]))
    assert math.degrees(gamma_crystal) == pytest.approx(20.5804, abs=1e-4)

    UB = _make_UB(0.0)
    assert np.linalg.det(UB) == pytest.approx(1.0, abs=1e-9)
    assert UB @ UB.T == pytest.approx(np.eye(3), abs=1e-9)

    G_lab, z_lab = lab_vectors_from_UB(HKL, (GAN_A, GAN_C), UB)
    assert np.linalg.norm(G_lab) == pytest.approx(np.linalg.norm(G_crystal), rel=1e-6)

    gamma_lab = gamma_from_vectors(G_lab, z_lab)
    assert math.degrees(gamma_lab) == pytest.approx(math.degrees(gamma_crystal), abs=1e-5)


def test_UB_without_B_gives_wrong_magnitude():
    """Guard against the composition error: UB @ [h,k,l] omits the lattice metric."""
    UB = _make_UB(0.0)
    wrong = np.linalg.norm(UB @ np.array(HKL, dtype=float))
    assert wrong != pytest.approx(6.47205, rel=1e-3)
    # It is in fact |[1,0,5]| = sqrt(26), since UB is a pure rotation.
    assert wrong == pytest.approx(math.sqrt(26.0), rel=1e-9)


# ── §3.2 — pixel ↔ direction round trip (NEW) ────────────────────────────────

def test_pixel_direction_round_trip():
    rng = np.random.default_rng(0)
    cols = rng.uniform(20, 2040, 200)
    rows = rng.uniform(20, 2140, 200)

    uf = pixel_to_direction(cols, rows, GEOM)
    back_col, back_row = direction_to_pixel(uf, GEOM)

    assert np.abs(back_col - cols).max() < 1e-6
    assert np.abs(back_row - rows).max() < 1e-6


def test_detector_reference_point_two_theta():
    """At (xcen, ycen) the line of sight is normal to the detector: 2θ = 90 − xbet."""
    uf = pixel_to_direction(GEOM.xcen, GEOM.ycen, GEOM)
    assert float(two_theta_from_direction(uf)) == pytest.approx(90.0 - GEOM.xbet, abs=1e-6)


def test_direction_to_pixel_rejects_rays_missing_the_detector():
    with pytest.raises(ValueError, match='does not intersect'):
        direction_to_pixel(np.array([0.0, 0.0, -1.0]), GEOM)


@pytest.mark.skipif(not HAS_LAUETOOLS, reason='LaueTools not installed')
def test_projection_matches_lauetools():
    """The tilt convention must be LaueTools', not a re-derivation.

    Both tilts are well under 1°, so a sign inversion would produce a small
    discrepancy invisible by eye — this is the test that catches it.
    """
    rng = np.random.default_rng(1)
    cols = rng.uniform(50, 2000, 100)
    rows = rng.uniform(50, 2100, 100)

    uf_ours = pixel_to_direction(cols, rows, GEOM)
    uf_lt, _ = calc_uflab(cols, rows, GEOM.calib, returnAngles=0,
                          pixelsize=GEOM.pixelsize, kf_direction='Z>0')
    assert np.abs(uf_ours - np.asarray(uf_lt)).max() < 1e-12

    col_ours, row_ours = direction_to_pixel(uf_ours, GEOM)
    col_lt, row_lt, _ = calc_xycam(np.asarray(uf_lt), GEOM.calib,
                                   pixelsize=GEOM.pixelsize)
    assert np.abs(col_ours - col_lt).max() < 1e-9
    assert np.abs(row_ours - row_lt).max() < 1e-9


# ── §4.3 — regression guard on the legacy path ───────────────────────────────

MONO_REFERENCE_PEAKS = [
    _peak(-3, -66.0), _peak(-2, -44.0), _peak(-1, -22.0), _peak(0, 0.0),
    _peak(1, 22.0), _peak(2, 44.0), _peak(3, 66.0),
]


def test_monochromatic_path_unchanged():
    """Frozen numerical output of the monochromatic route.

    This test must fail if anyone alters the legacy behaviour.  The values were
    produced by the implementation as it stood before the Laue routes existed.
    """
    res = layer_period_from_peaks(
        MONO_REFERENCE_PEAKS,
        pixel_size_mm=0.075,
        detector_distance_mm=200.0,
        wavelength_angstrom=0.727,
        two_theta_0_deg=43.9778,
        chi_deg=20.5804,
    )
    assert res['period_angstrom'] == pytest.approx(171.81041704596785, rel=1e-12)
    assert res['period_nm']       == pytest.approx(17.181041704596787, rel=1e-12)
    assert res['delta_q_inv_ang'] == pytest.approx(0.03657045605970749, rel=1e-12)
    assert res['method'] == 'monochromatic'
    assert [p['orders'] for p in res['per_pair']] == [(-3, -2), (-2, -1), (1, 2), (2, 3)]


def test_monochromatic_is_the_default_method():
    kw = dict(pixel_size_mm=0.075, detector_distance_mm=200.0, wavelength_angstrom=0.727)
    a = layer_period_from_peaks(MONO_REFERENCE_PEAKS, method='monochromatic', **kw)
    b = layer_period_from_peaks(MONO_REFERENCE_PEAKS, **kw)
    assert a['period_angstrom'] == b['period_angstrom']


def test_monochromatic_ignores_laue_parameters():
    """Laue-only kwargs must not perturb the legacy numbers."""
    kw = dict(pixel_size_mm=0.075, detector_distance_mm=200.0, wavelength_angstrom=0.727)
    base = layer_period_from_peaks(MONO_REFERENCE_PEAKS, **kw)
    with_laue = layer_period_from_peaks(
        MONO_REFERENCE_PEAKS, hkl=HKL, lattice=(GAN_A, GAN_C),
        UB=_make_UB(0.0), detector=GEOM, crop_origin_px=(0, 0),
        phi_deg=45.0, satellite_axis_psi_deg=12.0, **kw
    )
    assert base['period_angstrom'] == with_laue['period_angstrom']


# ── §3.5 — forward round trip in pixel space (REVISED §4.4) ─────────────────

# ── ADDENDUM 2 §5.1 — the exact separation formula ───────────────────────────

def test_angular_separation_formula():
    """Spherical law of cosines must reproduce the dot-product angle exactly."""
    rng = np.random.default_rng(3)
    cols = rng.uniform(50, 2000, 300)
    rows = rng.uniform(50, 2100, 300)
    uf = pixel_to_direction(cols, rows, GEOM)
    tt, chi = direction_to_2theta_chi(uf)

    i, j = rng.integers(0, 300, 500), rng.integers(0, 300, 500)
    keep = i != j
    i, j = i[keep], j[keep]

    true_ang = np.arccos(np.clip(np.sum(uf[i] * uf[j], axis=1), -1.0, 1.0))
    formula  = angular_separation(tt[i], chi[i], tt[j], chi[j])
    assert np.abs(true_ang - formula).max() < 1e-9


def test_two_theta_chi_round_trip():
    rng = np.random.default_rng(4)
    cols = rng.uniform(50, 2000, 200)
    rows = rng.uniform(50, 2100, 200)
    uf = pixel_to_direction(cols, rows, GEOM)
    tt, chi = direction_to_2theta_chi(uf)
    assert two_theta_chi_to_direction(tt, chi) == pytest.approx(uf, abs=1e-12)


@pytest.mark.skipif(not HAS_LAUETOOLS, reason='LaueTools not installed')
def test_angular_convention_matches_lauetools():
    """ADDENDUM 2 §4: the convention must be LaueTools', not an assumption.

    2θ = arccos(uf_y), χ = arctan(−uf_x/uf_z) — read from calc_uflab, not derived.
    """
    rng = np.random.default_rng(5)
    cols = rng.uniform(50, 2000, 200)
    rows = rng.uniform(50, 2100, 200)

    tt_lt, chi_lt = calc_uflab(cols, rows, GEOM.calib, returnAngles=1,
                               pixelsize=GEOM.pixelsize, kf_direction='Z>0')
    tt_us, chi_us = pixels_to_2theta_chi(cols, rows, GEOM)

    assert np.abs(tt_us - np.asarray(tt_lt)).max() < 1e-10
    assert np.abs(chi_us - np.asarray(chi_lt)).max() < 1e-10


def test_no_branch_crossing_on_this_detector():
    """χ's arctan fold is harmless only because uf_z > 0 across the whole frame."""
    rng = np.random.default_rng(6)
    cols = rng.uniform(0, GEOM.framedim[1], 400)
    rows = rng.uniform(0, GEOM.framedim[0], 400)
    uf = pixel_to_direction(cols, rows, GEOM)
    assert uf[:, 2].min() > 0.0
    assert_no_branch_crossing(uf)

    with pytest.raises(ValueError, match='uf_z'):
        assert_no_branch_crossing(np.array([[0.0, 0.5, -0.866]]))


# ── ADDENDUM 2 §5.3 — separation methods against fixtures ───────────────────

def _train_geometry(phi_deg: float):
    """Satellite (2θ, χ) for orders 0..3 with the train at a chosen orientation.

    φ = 0 puts the train radial, φ = 90° azimuthal — the two extremes of §2.
    """
    gamma = gamma_from_hkl(*HKL, GAN_A, GAN_C)
    G_mag = G_magnitude(*HKL, GAN_A, GAN_C)
    theta = theta_from_G(G_mag, LAM)
    az = math.radians(75.0)
    G0h = np.array([math.cos(theta) * math.cos(az), -math.sin(theta),
                    math.cos(theta) * math.sin(az)])

    p = LAB_KI - (LAB_KI @ G0h) * G0h
    p /= np.linalg.norm(p)
    q = np.cross(G0h, p)

    phi = math.radians(phi_deg)
    e_in = math.cos(phi) * p - math.sin(phi) * q
    z_lab = math.cos(gamma) * G0h + math.sin(gamma) * e_in
    return predict_satellite_angles(G_mag * G0h, z_lab, LAMBDA_TRUE, (0, 1, 2, 3))


@pytest.mark.parametrize('phi_deg, expected_deg', [
    (0.0,  0.399411),     # radial
    (45.0, 0.301574),
    (90.0, 0.149550),     # azimuthal
])
def test_separation_methods_against_fixtures(phi_deg, expected_deg):
    tt, chi = _train_geometry(phi_deg)
    exact = math.degrees(float(angular_separation(tt[0], chi[0], tt[1], chi[1])))
    # abs=1e-6, not rel: the spec quotes these to six decimals, so a tighter
    # tolerance would only be testing the rounding of the fixture.
    assert exact == pytest.approx(expected_deg, abs=1e-6)

    # Weighted quadrature is the correct local metric and must track the exact
    # value; naive quadrature and Δ(2θ)-only must not.
    d_tt  = abs(tt[1] - tt[0])
    d_chi = abs(chi[1] - chi[0])
    weighted = math.hypot(d_tt, math.sin(math.radians(tt[0])) * d_chi)
    assert weighted == pytest.approx(exact, rel=5e-4)


@pytest.mark.parametrize('phi_deg, d2theta_only, naive', [
    (0.0,  0.399411, 0.399411),
    (45.0, 0.282566, 0.320921),
    (90.0, 0.000281, 0.215372),
])
def test_documented_failure_modes(phi_deg, d2theta_only, naive):
    """Documents the failure modes rather than permitting them.

    Δ(2θ) alone collapses to 0.000281° against a true 0.149550° when the train is
    azimuthal — it would report no separation where a clear one exists.  Naive
    quadrature overshoots by +44 % in the same case.
    """
    tt, chi = _train_geometry(phi_deg)
    d_tt  = abs(tt[1] - tt[0])
    d_chi = abs(chi[1] - chi[0])
    assert d_tt == pytest.approx(d2theta_only, abs=1e-5)
    assert math.hypot(d_tt, d_chi) == pytest.approx(naive, abs=1e-5)


def test_nonuniform_spacing_survives_train_orientation():
    """The 1.8 %/step contraction is the discriminating signature and is intrinsic."""
    for phi_deg in (0.0, 45.0, 90.0):
        tt, chi = _train_geometry(phi_deg)
        seps = np.array([float(angular_separation(tt[k], chi[k], tt[k+1], chi[k+1]))
                         for k in range(3)])
        ratios = seps / seps[0]
        assert ratios[1] == pytest.approx(0.9816, abs=0.001)
        assert ratios[2] == pytest.approx(0.9636, abs=0.001)


# ── ADDENDUM 2 §5.4 — round trip in angular space (replaces §3.5) ───────────

@pytest.mark.parametrize('spin_deg', [0.0, 45.0, 90.0, 137.0])
def test_forward_model_round_trip_angular(spin_deg):
    """Λ recovered from model-generated angles, independent of crystal orientation.

    The orientation sweep replaces the φ sweep of the parent spec and is the test
    that catches convention inversions — it must not be reduced to one case.
    """
    UB = _make_UB(spin_deg)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)

    res = layer_period_from_peaks(
        peaks, wavelength_angstrom=LAM, method='laue_forward',
        hkl=HKL, lattice=(GAN_A, GAN_C),
        detector=GEOM, UB=UB, crop_origin_px=crop_origin,
    )
    assert res['method'] == 'laue_forward'
    assert res['period_angstrom'] == pytest.approx(LAMBDA_TRUE, rel=1e-3)
    assert res['fit_rms_deg'] < 1e-6
    assert res['parent_offset_deg'] < 1e-6
    assert res['train_delta_deg'] < 1e-3


def test_laue_forward_period_never_uses_the_order_zero_peak():
    """Λ comes from satellite-satellite pairs only.

    The order-0 peak is the bulk reflection in an MQW (§4.13), so letting it
    into the fit would put a non-superlattice feature in the period. Moving it
    anywhere must therefore leave Λ untouched — it may only affect
    `parent_offset_deg`, which is a UB/calibration diagnostic.
    """
    UB = _make_UB(45.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)
    kw = dict(wavelength_angstrom=LAM, method='laue_forward', hkl=HKL,
              lattice=(GAN_A, GAN_C), detector=GEOM, UB=UB,
              crop_origin_px=crop_origin)

    res = layer_period_from_peaks(peaks, **kw)
    assert all(0 not in pair['orders'] for pair in res['per_pair'])

    displaced = []
    for pk in peaks:
        pk = dict(pk)
        if pk['order'] == 0:
            r, c = pk['position_2d']
            pk['position_2d'] = (r + 7.0, c + 7.0)
            pk['pos_along_axis'] = pk['pos_along_axis'] + 7.0
        displaced.append(pk)

    assert layer_period_from_peaks(displaced, **kw)['period_angstrom'] == pytest.approx(
        res['period_angstrom'], rel=1e-12)


@pytest.mark.parametrize('spin_deg', [0.0, 45.0, 90.0, 137.0])
def test_synthetic_geometry_is_physical(spin_deg):
    """The fixture must be self-consistent, or the round trip tests nothing.

    The parent spot has to land on the frame and at the 2θ that indexing implies
    for λ = 0.727 Å; the spin must actually move the satellites, otherwise the
    orientation sweep is vacuous.
    """
    UB = _make_UB(spin_deg)
    G_lab, _ = lab_vectors_from_UB(HKL, (GAN_A, GAN_C), UB)
    col, row = direction_to_pixel(kf_hat(G_lab, LAB_KI), GEOM)

    n_rows, n_cols = GEOM.framedim
    assert 0 <= row < n_rows and 0 <= col < n_cols

    two_theta = float(two_theta_from_direction(pixel_to_direction(col, row, GEOM)))
    theta = theta_from_G(G_magnitude(*HKL, GAN_A, GAN_C), LAM)
    assert two_theta == pytest.approx(2.0 * math.degrees(theta), abs=1e-3)

    peaks, _ = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)
    p2d = {p['order']: p['position_2d'] for p in peaks}
    sep = math.hypot(p2d[1][0] - p2d[0][0], p2d[1][1] - p2d[0][1])
    assert 1.0 < sep < BOXSIZE


def test_forward_model_recovers_period_over_a_range():
    UB = _make_UB(0.0)
    for true_period in (60.0, 97.0, 150.0):
        peaks, crop_origin = _synthetic_pixel_peaks(true_period, UB)
        res = layer_period_from_peaks(
            peaks, wavelength_angstrom=LAM, method='laue_forward',
            hkl=HKL, lattice=(GAN_A, GAN_C),
            detector=GEOM, UB=UB, crop_origin_px=crop_origin,
        )
        assert res['period_angstrom'] == pytest.approx(true_period, rel=1e-3)


def test_forward_model_reports_derived_geometry():
    UB = _make_UB(0.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)
    res = layer_period_from_peaks(
        peaks, wavelength_angstrom=LAM, method='laue_forward',
        hkl=HKL, lattice=(GAN_A, GAN_C),
        detector=GEOM, UB=UB, crop_origin_px=crop_origin,
    )
    assert res['gamma_deg']   == pytest.approx(20.5804, abs=1e-3)
    assert res['theta_deg']   == pytest.approx(21.9889, abs=1e-3)
    assert res['G_magnitude'] == pytest.approx(6.47205, rel=1e-5)
    # 2θ measured through the .det must agree with 2θ from indexing.  On real
    # data a mismatch means the ROI is not on the reflection that was indexed.
    assert res['two_theta_measured'] == pytest.approx(res['two_theta_deg'], abs=0.05)


def test_two_theta_measured_is_the_parent_not_the_satellite_mean():
    """The satellites sit along the train, so their mean 2θ is offset by design.

    Reporting that mean as `two_theta_measured` made a correct dataset look like
    it disagreed with indexing by ~1°.  The comparable quantity is the parent's.
    """
    UB = _make_UB(90.0)          # spin 90: the train is mostly radial here
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1, 0])
    row0, col0 = crop_origin
    res = layer_period_from_peaks(
        peaks, wavelength_angstrom=LAM, method='laue_forward',
        hkl=HKL, lattice=(GAN_A, GAN_C),
        detector=GEOM, UB=UB, crop_origin_px=crop_origin,
    )

    # two_theta_measured must be the parent's own 2θ, computed independently.
    parent = next(p for p in peaks if p['order'] == 0)
    tt_parent, _ = pixels_to_2theta_chi(col0 + parent['position_2d'][1],
                                        row0 + parent['position_2d'][0], GEOM)
    assert res['two_theta_measured'] == pytest.approx(float(tt_parent[0]), abs=1e-9)
    assert res['two_theta_measured'] == pytest.approx(res['two_theta_deg'], abs=0.05)

    # two_theta_satellites is the mean over the satellite orders — a different
    # quantity, and the one that must NOT be compared against indexing.
    sats = [p for p in peaks if p['order'] != 0]
    tt_s, _ = pixels_to_2theta_chi(
        [col0 + p['position_2d'][1] for p in sats],
        [row0 + p['position_2d'][0] for p in sats], GEOM)
    assert res['two_theta_satellites'] == pytest.approx(float(np.mean(tt_s)), abs=1e-9)
    assert res['two_theta_satellites'] != pytest.approx(res['two_theta_measured'],
                                                        abs=0.1)


def test_forward_route_takes_no_psi():
    """§2.3: the satellite axis is an output of the model, not an input."""
    UB = _make_UB(0.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)
    kw = dict(wavelength_angstrom=LAM, method='laue_forward', hkl=HKL,
              lattice=(GAN_A, GAN_C), detector=GEOM, UB=UB,
              crop_origin_px=crop_origin)
    a = layer_period_from_peaks(peaks, **kw)
    b = layer_period_from_peaks(peaks, satellite_axis_psi_deg=37.0, **kw)
    assert a['period_angstrom'] == b['period_angstrom']


@pytest.mark.parametrize('spin_deg', [0.0, 45.0, 90.0])
def test_train_direction_replaces_the_withdrawn_axis_test(spin_deg):
    """ADDENDUM 2 §4 withdraws the axis_angle comparison; this is its replacement.

    Same idea — the train direction is predicted from the crystal orientation
    with no free parameter — but expressed in the calibrated angular space
    instead of the ad-hoc ``axis_angle`` metric, which must not enter any
    calculation.
    """
    UB = _make_UB(spin_deg)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)
    res = layer_period_from_peaks(
        peaks, wavelength_angstrom=LAM, method='laue_forward',
        hkl=HKL, lattice=(GAN_A, GAN_C),
        detector=GEOM, UB=UB, crop_origin_px=crop_origin,
    )
    assert res['train_delta_deg'] < 1e-3


def test_train_direction_delta_detects_a_rotated_train():
    """A train rotated in angular space must register, or the diagnostic is blind."""
    tt = np.array([43.0, 43.1, 43.2])
    chi = np.array([10.0, 10.0, 10.0])          # purely radial
    same = train_direction_delta_deg(tt, chi, tt, chi)
    assert same == pytest.approx(0.0, abs=1e-9)

    tt_rot = np.array([43.0, 43.0, 43.0])       # purely azimuthal
    chi_rot = np.array([10.0, 10.1, 10.2])
    turned = train_direction_delta_deg(tt_rot, chi_rot, tt, chi)
    assert turned == pytest.approx(90.0, abs=1e-6)


# ── §4.5 — the analytic route's known bias ───────────────────────────────────

def _first_pair_peaks(phi_deg: float):
    """Two peaks carrying the 0→1 model separation, for the analytic route.

    The analytic route derives Λ from a single Δψ and is order-agnostic, so the
    0→1 separation rides on labels (1, 2) — the period routes exclude any pair
    touching SL0, whose fitted position is contaminated by the bulk Bragg peak.
    """
    gamma = gamma_from_hkl(*HKL, GAN_A, GAN_C)
    G_mag = G_magnitude(*HKL, GAN_A, GAN_C)
    theta = theta_from_G(G_mag, LAM)
    G0_hat, z_lab, u_hat = build_canonical_frame(gamma, theta, math.radians(phi_deg))
    sep = predict_angular_separations(G_mag * G0_hat, z_lab, LAMBDA_TRUE, (0, 1), u_hat)[0]
    two_theta = 2.0 * math.degrees(theta)
    dx = float(sep) * 200.0 / (0.075 * math.cos(math.radians(two_theta)) ** 2)
    return [_peak(1, 0.0), _peak(2, dx)]


def test_analytic_route_matches_known_bias():
    """Pins the +0.94 % small-angle bias so a future change is flagged, not absorbed."""
    res = layer_period_from_peaks(
        _first_pair_peaks(0.0),
        pixel_size_mm=0.075, detector_distance_mm=200.0,
        wavelength_angstrom=LAM, method='laue_analytic',
        hkl=HKL, lattice=(GAN_A, GAN_C), phi_deg=0.0, satellite_axis_psi_deg=0.0,
    )
    assert res['period_angstrom'] == pytest.approx(97.909, abs=0.01)
    assert res['method'] == 'laue_analytic'


# ── §4.6 — the non-uniform spacing signature ─────────────────────────────────

@pytest.mark.parametrize('phi_deg', [0.0, 45.0, 90.0])
def test_nonuniform_spacing_signature(phi_deg):
    gamma = gamma_from_hkl(*HKL, GAN_A, GAN_C)
    G_mag = G_magnitude(*HKL, GAN_A, GAN_C)
    theta = theta_from_G(G_mag, LAM)
    G0_hat, z_lab, u_hat = build_canonical_frame(gamma, theta, math.radians(phi_deg))

    seps = predict_angular_separations(
        G_mag * G0_hat, z_lab, LAMBDA_TRUE, (0, 1, 2, 3), u_hat
    )
    ratios = seps / seps[0]
    assert ratios[0] == pytest.approx(1.0000, abs=1e-9)
    assert ratios[1] == pytest.approx(0.9816, abs=0.001)
    assert ratios[2] == pytest.approx(0.9636, abs=0.001)


# ── §4.7 — the physical singularity must raise ───────────────────────────────

def test_symmetric_reflection_raises_analytic():
    with pytest.raises(ValueError, match='symmetric reflection'):
        layer_period_from_peaks(
            [_peak(1, 0.0), _peak(2, 30.0)],
            pixel_size_mm=0.075, detector_distance_mm=200.0,
            wavelength_angstrom=LAM, method='laue_analytic',
            hkl=(0, 0, 2), lattice=(GAN_A, GAN_C),
            phi_deg=0.0, satellite_axis_psi_deg=0.0,
        )


def test_symmetric_reflection_raises_forward():
    """(002) has γ = 0: satellites are degenerate, no period exists to extract."""
    UB = _make_UB(0.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)
    with pytest.raises(ValueError, match='symmetric reflection'):
        layer_period_from_peaks(
            peaks, wavelength_angstrom=LAM, method='laue_forward',
            hkl=(0, 0, 2), lattice=(GAN_A, GAN_C),
            detector=GEOM, UB=np.eye(3), crop_origin_px=crop_origin,
        )


# ── API contract guard rails (§6, §7, addendum §2.4) ─────────────────────────

def test_unknown_method_raises():
    with pytest.raises(ValueError, match='Unknown method'):
        layer_period_from_peaks(
            MONO_REFERENCE_PEAKS, pixel_size_mm=0.075,
            detector_distance_mm=200.0, wavelength_angstrom=0.727, method='laue',
        )


def test_forward_requires_detector_and_UB():
    UB = _make_UB(0.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)
    with pytest.raises(ValueError, match='detector'):
        layer_period_from_peaks(
            peaks, wavelength_angstrom=LAM, method='laue_forward',
            hkl=HKL, lattice=(GAN_A, GAN_C), crop_origin_px=crop_origin,
        )


def test_forward_requires_crop_origin():
    UB = _make_UB(0.0)
    peaks, _ = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)
    with pytest.raises(ValueError, match='crop_origin_px'):
        layer_period_from_peaks(
            peaks, wavelength_angstrom=LAM, method='laue_forward',
            hkl=HKL, lattice=(GAN_A, GAN_C), detector=GEOM, UB=UB,
        )


def test_analytic_requires_explicit_psi():
    """No silent default: defaulting a geometry angle to 0 has caused a wrong result once."""
    with pytest.raises(ValueError, match='satellite_axis_psi_deg'):
        layer_period_from_peaks(
            _first_pair_peaks(0.0), pixel_size_mm=0.075,
            detector_distance_mm=200.0, wavelength_angstrom=LAM,
            method='laue_analytic', hkl=HKL, lattice=(GAN_A, GAN_C), phi_deg=0.0,
        )


def test_laue_requires_hkl_and_lattice():
    with pytest.raises(ValueError, match='hkl'):
        layer_period_from_peaks(
            _first_pair_peaks(0.0), pixel_size_mm=0.075,
            detector_distance_mm=200.0, wavelength_angstrom=LAM,
            method='laue_analytic', phi_deg=0.0, satellite_axis_psi_deg=0.0,
        )


def test_forward_requires_two_satellite_orders():
    UB = _make_UB(0.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[0, 1])
    with pytest.raises(ValueError, match='at least two'):
        layer_period_from_peaks(
            peaks, wavelength_angstrom=LAM, method='laue_forward',
            hkl=HKL, lattice=(GAN_A, GAN_C), detector=GEOM, UB=UB,
            crop_origin_px=crop_origin,
        )


def test_detector_rejects_unsupported_kf_direction():
    with pytest.raises(NotImplementedError, match='kf_direction'):
        DetectorGeometry(**DET_KW, kf_direction='X>0')


# ── .det reading and UB provenance ───────────────────────────────────────────

DET_FILE_TEXT = """69.98400, 1079.5700, 983.7300, 0.1730000, 0.3820000, 0.07500000, 2162, 2068
Sample-Detector distance(IM), xO, yO, angle1, angle2, pixelsize, dim1, dim2
Calibration done with Ge at Fri May 22 15:55:30 2026 with LaueToolsGUI.py
Experimental Data file: /data/RAW_DATA/MLed/MLed_Ref_Ge_0002/scan0002/ge.dat
Orientation Matrix:
[[-0.5552371,-0.5225988,-0.6469948],[0.6799375,-0.7332180,0.0087363],[-0.4789538,-0.4350653,0.7624444]]
# Material : Ge
# dd : 69.984
# xcen : 1079.57
# ycen : 983.73
# xbet : 0.173
# xgam : 0.382
# pixelsize : 0.075000002
# CCDLabel : EIGER_4MCdTe
# framedim : (2162, 2068)
# kf_direction : Z>0
"""


@pytest.fixture
def det_file(tmp_path):
    p = tmp_path / 'refGe.det'
    p.write_text(DET_FILE_TEXT)
    return p


@pytest.mark.skipif(not HAS_LAUETOOLS, reason='LaueTools not installed')
def test_from_det_file_reshapes_matrix(det_file):
    """readfile_det hands back a flat 9-element array; it must become 3x3."""
    geom, UB = DetectorGeometry.from_det_file(det_file)
    assert UB.shape == (3, 3)
    assert np.linalg.det(UB) == pytest.approx(1.0, abs=1e-6)
    assert UB @ UB.T == pytest.approx(np.eye(3), abs=1e-6)
    assert UB[0, 0] == pytest.approx(-0.5552371, abs=1e-7)
    assert UB[2, 2] == pytest.approx(0.7624444, abs=1e-7)


@pytest.mark.skipif(not HAS_LAUETOOLS, reason='LaueTools not installed')
def test_from_det_file_parses_geometry_and_metadata(det_file):
    geom, _ = DetectorGeometry.from_det_file(det_file)
    assert geom.dd        == pytest.approx(69.984)
    assert geom.xcen      == pytest.approx(1079.57)
    assert geom.ycen      == pytest.approx(983.73)
    assert geom.xbet      == pytest.approx(0.173)
    assert geom.xgam      == pytest.approx(0.382)
    assert geom.pixelsize == pytest.approx(0.075, abs=1e-6)
    assert geom.framedim  == (2162, 2068)
    assert geom.material  == 'Ge'
    assert geom.ccd_label == 'EIGER_4MCdTe'


@pytest.mark.skipif(not HAS_LAUETOOLS, reason='LaueTools not installed')
def test_ub_from_calibration_crystal_is_rejected(det_file):
    """A Ge calibration carries Ge's orientation, not the sample's.

    Using it as the sample UB produces a confident, meaningless period — so the
    mismatch has to raise rather than be discovered downstream.
    """
    geom, _ = DetectorGeometry.from_det_file(det_file)
    with pytest.raises(ValueError, match="calibrated with 'Ge'"):
        assert_ub_material(geom, 'GaN')
    assert_ub_material(geom, 'Ge')       # matching material must not raise
    assert_ub_material(geom, 'ge')       # comparison is case-insensitive


def test_assert_ub_material_is_silent_when_material_unknown():
    """Hand-built geometries carry no provenance and must not be blocked."""
    assert_ub_material(GEOM, 'GaN')


# ── Laboratory-frame convention of the UB ────────────────────────────────────

# The real GaN orientation matrix for the MLed scan, as delivered by indexing.
# It is a perfect rotation and gives the right |G| and γ, but it is expressed in
# a beam-∥-x frame while LaueTools uses beam ∥ +y.
UB_MLED_RAW = np.array([
    [0.6790713826270244, -0.33435394586139133, -0.6535055441110957],
    [0.449920964168808,   0.8930050765548248,   0.010632932273113219],
    [0.5800286055863394, -0.30124636451620795,  0.7568470417246379]])

# Measured (2θ, χ) of the GaN 105 parent for the MLed scan, from the .det.
MLED_GEOM = DetectorGeometry(dd=69.984, xcen=1079.57, ycen=983.73,
                             xbet=0.173, xgam=0.382, pixelsize=0.075,
                             framedim=(2162, 2068))
MLED_LATTICE = (3.189, 5.185)
MLED_TT, MLED_CHI = 43.9586, 10.5324


def test_real_ub_is_a_proper_rotation():
    assert np.linalg.det(UB_MLED_RAW) == pytest.approx(1.0, abs=1e-9)
    assert UB_MLED_RAW @ UB_MLED_RAW.T == pytest.approx(np.eye(3), abs=1e-12)


def test_wrong_frame_still_gives_right_G_and_gamma():
    """This is why a frame error is dangerous: the crystallography looks fine.

    |G| and γ are frame-independent, so every sanity check short of projecting
    onto the detector passes.  Only the spot position exposes the mistake.
    """
    for UB in (UB_MLED_RAW, ub_from_beam_x_frame(UB_MLED_RAW)):
        G_lab, z_lab = lab_vectors_from_UB((1, 0, 5), MLED_LATTICE, UB)
        assert np.linalg.norm(G_lab) == pytest.approx(6.47205, rel=1e-5)
        assert math.degrees(gamma_from_vectors(G_lab, z_lab)) == pytest.approx(
            20.5804, abs=1e-3)


def test_beam_x_frame_conversion_places_the_parent_reflection():
    """The corrected frame must put GaN 105 on the measured spot; the raw one must not."""
    raw = lab_vectors_from_UB((1, 0, 5), MLED_LATTICE, UB_MLED_RAW)[0]
    tt_raw, chi_raw = direction_to_2theta_chi(kf_hat(raw, LAB_KI))
    sep_raw = math.degrees(float(angular_separation(tt_raw, chi_raw, MLED_TT, MLED_CHI)))

    fixed = lab_vectors_from_UB((1, 0, 5), MLED_LATTICE,
                                ub_from_beam_x_frame(UB_MLED_RAW))[0]
    tt_fix, chi_fix = direction_to_2theta_chi(kf_hat(fixed, LAB_KI))
    sep_fix = math.degrees(float(angular_separation(tt_fix, chi_fix, MLED_TT, MLED_CHI)))

    assert sep_raw > 20.0        # as given: nowhere near
    assert sep_fix < 0.25        # converted: on the spot


def test_diagnose_ub_frame_identifies_the_right_convention():
    frames = diagnose_ub_frame(UB_MLED_RAW, (1, 0, 5), MLED_LATTICE,
                               MLED_TT, MLED_CHI)
    assert frames['best'] == 'beam ∥ x → y'
    assert frames['beam ∥ x → y'] < 0.25
    # The identification is only meaningful if the alternatives are far away.
    others = [v for k, v in frames.items()
              if k not in ('best', 'beam ∥ x → y')]
    assert min(others) > 2.0


def test_beam_x_conversion_is_a_rotation_about_z():
    """(x, y, z) → (−y, x, z): a beam along +x becomes a beam along +y."""
    assert np.linalg.det(BEAM_X_TO_Y) == pytest.approx(1.0, abs=1e-12)
    assert BEAM_X_TO_Y @ np.array([1.0, 0.0, 0.0]) == pytest.approx(LAB_KI)


def test_real_ub_predicts_the_measured_train_direction():
    """No-free-parameter check: the train direction follows from the orientation alone.

    The measured axis_angle is used here as CONVENTION EVIDENCE only — never as an
    input to a fit (ADDENDUM 2 §4).
    """
    UB = ub_from_beam_x_frame(UB_MLED_RAW)
    G_lab, z_lab = lab_vectors_from_UB((1, 0, 5), MLED_LATTICE, UB)
    col, row = predict_satellite_pixels(G_lab, z_lab, 97.0, [0, -1, -2, -3], MLED_GEOM)
    ang = math.degrees(math.atan2(row[-1] - row[0], col[-1] - col[0]))
    ang = (ang + 90.0) % 180.0 - 90.0
    assert ang == pytest.approx(-83.7, abs=1.5)     # measured axis_angle


def test_real_ub_selects_a_plausible_wavelength():
    """In white beam λ is selected, not imposed — it must land near the nominal."""
    UB = ub_from_beam_x_frame(UB_MLED_RAW)
    G_lab, _ = lab_vectors_from_UB((1, 0, 5), MLED_LATTICE, UB)
    tt, _ = direction_to_2theta_chi(kf_hat(G_lab, LAB_KI))
    lam = 4 * math.pi * math.sin(math.radians(tt / 2)) / np.linalg.norm(G_lab)
    assert lam == pytest.approx(0.7267, rel=0.01)


# ── Absolute order assignment ────────────────────────────────────────────────

def test_order_assignment_detects_correct_labelling():
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1, 0])
    res = check_order_assignment(
        peaks, hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB, detector=GEOM,
        crop_origin_px=crop_origin, period_angstrom=LAMBDA_TRUE)
    assert res['implied_offset'] == 0
    assert res['confident']


def test_order_assignment_detects_a_hidden_order():
    """Drop the true -1 and relabel: the SL0 gap must give it away."""
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(
        LAMBDA_TRUE, UB, orders=[-4, -3, -2, -1, 0])

    kept = [p for p in peaks if p['order'] in (0, -2, -3, -4)]
    relabelled = []
    for p in kept:
        q = dict(p)
        if q['order'] != 0:
            q['order'] += 1          # -2 -> -1, as the detector would label it
        relabelled.append(q)

    res = check_order_assignment(
        relabelled, hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB, detector=GEOM,
        crop_origin_px=crop_origin, period_angstrom=LAMBDA_TRUE)
    assert res['implied_offset'] == 1
    assert res['confident']


def test_order_assignment_gap_hypotheses_are_far_apart():
    """The discriminator works because the hypotheses differ by ~2x, not by 0.02 %."""
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1, 0])
    res = check_order_assignment(
        peaks, hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB, detector=GEOM,
        crop_origin_px=crop_origin, period_angstrom=LAMBDA_TRUE)
    g = res['predicted_gaps']
    assert g[1] / g[0] > 1.8          # one hidden order nearly doubles the gap


def test_order_assignment_needs_sl0():
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1])
    res = check_order_assignment(
        peaks, hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB, detector=GEOM,
        crop_origin_px=crop_origin, period_angstrom=LAMBDA_TRUE)
    assert res['implied_offset'] is None


# ── Locating SL0 without the order-0 peak (README.md, "The bright peak in the ROI is the bulk") ─────────────

# Frame 7354 of the MLed scan, exactly as detected.  The order-0 amplitude is
# 234x the nearest satellite while consecutive satellites differ by 3-6x.
MLED_REAL_PEAKS = [(-3, -51.86, 103.5), (-2, -37.24, 578.9),
                   (-1, -23.28, 1863.0), (0, -2.84, 436260.6)]
MLED_BOX, MLED_AXIS_DEG = 80, -83.7
MLED_CROP_ORIGIN = (1980 - MLED_BOX, 898 - MLED_BOX)
MLED_PERIOD_FITTED = 96.166725


def _mled_peaks(sl0_center_offset_px=0.0):
    """Rebuild the detected peak list the way ``_make_peak`` does.

    ``position_2d`` is reconstructed, not recorded, so it needs ``sl0_center`` —
    the centroid the 1-D profile was taken about.  That is NOT the crop centre:
    the segmentation ROI covers SL0 *and* the train, so it sits ~1.5 × spacing
    away (§4.10).  The offset shifts the absolute detector pixel, hence the
    local deg/px, hence the predicted SL0 by a few tenths of a pixel:

        offset  0 px -> SL0 at -9.15    offset 21 px -> SL0 at -9.46

    A real run of the notebook gives -9.5, consistent with the ~1.5 × spacing
    offset.  Tests below therefore assert the model-vs-ladder *agreement*, which
    is insensitive to this, rather than the absolute position, which is not.
    """
    rad = math.radians(MLED_AXIS_DEG)
    cr = MLED_BOX + sl0_center_offset_px * math.sin(rad)
    cc = MLED_BOX + sl0_center_offset_px * math.cos(rad)
    return [{'order': n, 'pos_along_axis': s, 'amplitude': a,
             'fwhm': 2.5, 'sigma': 2.5 / 2.3548,
             'position_2d': (cr + s * math.sin(rad), cc + s * math.cos(rad))}
            for n, s, a in MLED_REAL_PEAKS]


def _mled_kwargs():
    return dict(hkl=(1, 0, 5), lattice=MLED_LATTICE,
                UB=ub_from_beam_x_frame(UB_MLED_RAW), detector=MLED_GEOM,
                crop_origin_px=MLED_CROP_ORIGIN,
                period_angstrom=MLED_PERIOD_FITTED)


def _displace_order0(peaks, fraction):
    """Move the order-0 peak by `fraction` of one step, along the train."""
    p0 = next(p for p in peaks if p['order'] == 0)
    p1 = min((p for p in peaks if p['order'] != 0), key=lambda p: abs(p['order']))
    d_pos = p1['pos_along_axis'] - p0['pos_along_axis']
    d_row = p1['position_2d'][0] - p0['position_2d'][0]
    d_col = p1['position_2d'][1] - p0['position_2d'][1]
    out = []
    for p in peaks:
        q = dict(p)
        if q['order'] == 0:
            q['pos_along_axis'] = p0['pos_along_axis'] + fraction * d_pos
            q['position_2d'] = (p0['position_2d'][0] + fraction * d_row,
                                p0['position_2d'][1] + fraction * d_col)
        out.append(q)
    return out


def test_locate_sl0_recovers_a_detected_sl0():
    """When the order-0 peak really is SL0, the prediction must land on it."""
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1, 0])
    res = locate_sl0_from_ladder(
        peaks, hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB, detector=GEOM,
        crop_origin_px=crop_origin, period_angstrom=LAMBDA_TRUE, verbose=False)
    assert res['order0_is_sl0']
    assert res['sl0_pos_along_axis'] == pytest.approx(0.0, abs=0.3)
    assert res['bulk_sl0_offset_px'] == pytest.approx(0.0, abs=0.3)


def test_locate_sl0_never_reads_the_order_zero_peak():
    """The defining property: the prediction is independent of the bright peak.

    This is what makes step 2 a prediction rather than a restatement — Λ and the
    local scale both come from satellite-satellite gaps.  Move the order-0 peak
    anywhere and the predicted SL0 position must not budge.
    """
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1, 0])
    kw = dict(hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB, detector=GEOM,
              crop_origin_px=crop_origin, period_angstrom=LAMBDA_TRUE, verbose=False)

    base = locate_sl0_from_ladder(peaks, **kw)['sl0_pos_along_axis']
    for fraction in (-3.7, 0.5, 2.0, 11.3):
        moved = locate_sl0_from_ladder(_displace_order0(peaks, fraction), **kw)
        assert moved['sl0_pos_along_axis'] == pytest.approx(base, abs=1e-12)


def test_locate_sl0_flags_a_peak_that_is_off_the_ladder():
    """Half a step off is the bulk signature: not SL0, not a hidden order."""
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1, 0])
    res = locate_sl0_from_ladder(
        _displace_order0(peaks, 0.5), hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB,
        detector=GEOM, crop_origin_px=crop_origin,
        period_angstrom=LAMBDA_TRUE, verbose=False)
    assert not res['order0_is_sl0']
    assert abs(res['bulk_sl0_offset_px'] / res['gap_pred_px']) == pytest.approx(
        0.5, abs=0.05)


def test_locate_sl0_needs_two_satellites_for_the_local_scale():
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-1, 0])
    res = locate_sl0_from_ladder(
        peaks, hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB, detector=GEOM,
        crop_origin_px=crop_origin, period_angstrom=LAMBDA_TRUE, verbose=False)
    assert not res['confident']
    assert math.isnan(res['sl0_pos_along_axis'])


def test_locate_sl0_on_real_data_agrees_with_the_observed_ladder():
    """§4.13: two independent routes to SL0 agree to well under one step.

    The model uses the crystal orientation and the fitted Λ; the extrapolation
    below uses only the observed gap ratio and no crystallography at all.
    """
    pos = {n: s for n, s, _ in MLED_REAL_PEAKS}
    g21, g32 = pos[-1] - pos[-2], pos[-2] - pos[-3]
    sl0_ladder = pos[-1] + g21 / (g32 / g21)
    assert sl0_ladder == pytest.approx(-9.95, abs=0.1)   # uses pos_along_axis only

    # Swept over the plausible sl0_center offsets, because position_2d is
    # reconstructed here (see _mled_peaks).  The conclusion must not depend on it.
    for offset in (0.0, 10.5, 21.0, 28.0):
        res = locate_sl0_from_ladder(_mled_peaks(offset), verbose=False,
                                     **_mled_kwargs())
        assert res['sl0_pos_along_axis'] == pytest.approx(-9.4, abs=0.35)
        assert abs(res['sl0_pos_along_axis'] - sl0_ladder) < 0.25 * res['gap_pred_px']
        assert not res['order0_is_sl0']


def test_order_assignment_reports_the_bulk_instead_of_a_hidden_order():
    """The MQW case that motivated the change: 1.46 steps is not "1 or 2"."""
    res = check_order_assignment(_mled_peaks(), verbose=False, **_mled_kwargs())
    assert res['verdict'] == 'order0_off_ladder'
    assert res['implied_offset'] is None      # never a number that would be misread
    assert not res['confident']
    assert not res['order0_is_sl0']
    assert res['steps_from_sl0'] == pytest.approx(1.46, abs=0.05)
    assert res['sl0']['sl0_pos_along_axis'] == pytest.approx(-9.15, abs=0.1)


def test_amplitude_excess_is_independent_evidence_of_the_bulk():
    """Positions say off-ladder; intensities say bulk. Different observables."""
    res = check_order_assignment(_mled_peaks(), verbose=False, **_mled_kwargs())
    assert res['amplitude_excess'] == pytest.approx(73.0, abs=1.0)

    # ... and on a train whose order-0 peak really is SL0, there is no excess.
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1, 0])
    for p, amp in zip(sorted(peaks, key=lambda q: abs(q['order'])),
                      (5000.0, 1500.0, 450.0, 135.0)):
        p['amplitude'] = amp
    clean = check_order_assignment(
        peaks, hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB, detector=GEOM,
        crop_origin_px=crop_origin, period_angstrom=LAMBDA_TRUE, verbose=False)
    assert clean['amplitude_excess'] == pytest.approx(1.0, abs=0.05)


def test_half_step_is_never_reported_as_a_hidden_order():
    """A hidden order displaces by a WHOLE step; half a step is a different fault.

    Guards the specific misreading that produced the original wrong diagnosis.
    """
    UB = _make_UB(90.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1, 0])
    kw = dict(hkl=HKL, lattice=(GAN_A, GAN_C), UB=UB, detector=GEOM,
              crop_origin_px=crop_origin, period_angstrom=LAMBDA_TRUE, verbose=False)

    for fraction in (0.4, 0.5, 0.6, 1.5):
        res = check_order_assignment(_displace_order0(peaks, fraction), **kw)
        assert res['verdict'] == 'order0_off_ladder', f'fraction={fraction}'
        assert res['implied_offset'] is None

    # A whole step AWAY from the train, on the other hand, is exactly what one
    # hidden order looks like, and must still be reported as such.  (Negative
    # fraction: the displacement runs opposite to the nearest satellite.)
    res = check_order_assignment(_displace_order0(peaks, -1.0), **kw)
    assert res['verdict'] == 'hidden_order'
    assert res['implied_offset'] == 1


# ── The ROI centre is not the parent peak ────────────────────────────────────

def test_roi_centre_is_not_the_parent_peak():
    """A segmentation ROI covers SL0 *and* the train, so its centre is offset.

    With one-sided orders the offset is about 1.5 × spacing, which at this
    geometry is ~0.5° of 2θ — ten times the reprojection pass criterion.  Using
    the ROI centre as the measured parent position therefore fails the check for
    a reason that has nothing to do with the physics.
    """
    UB = _make_UB(0.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB, orders=[-3, -2, -1, 0])
    row0, col0 = crop_origin

    parent = next(p for p in peaks if p['order'] == 0)
    parent_col = col0 + parent['position_2d'][1]
    parent_row = row0 + parent['position_2d'][0]

    cols = [col0 + p['position_2d'][1] for p in peaks]
    rows = [row0 + p['position_2d'][0] for p in peaks]
    roi_col, roi_row = float(np.mean(cols)), float(np.mean(rows))

    tt_parent, chi_parent = pixels_to_2theta_chi(parent_col, parent_row, GEOM)
    tt_roi, chi_roi = pixels_to_2theta_chi(roi_col, roi_row, GEOM)
    offset = math.degrees(float(angular_separation(
        float(tt_parent[0]), float(chi_parent[0]),
        float(tt_roi[0]), float(chi_roi[0]))))

    # Well beyond the 0.05 deg criterion: the confusion is not a rounding issue.
    assert offset > 0.1

    # The fit uses the order-0 peak, so it is immune to the confusion.
    res = layer_period_from_peaks(
        peaks, wavelength_angstrom=LAM, method='laue_forward',
        hkl=HKL, lattice=(GAN_A, GAN_C),
        detector=GEOM, UB=UB, crop_origin_px=crop_origin,
    )
    assert res['parent_offset_deg'] < 1e-6


# ── Detector Jacobian, used by the analytic route only ───────────────────────

def test_pixel_to_angle_radial_matches_legacy_jacobian():
    two_theta, dx_px = 43.9778, 35.0
    got = pixel_to_angle(dx_px, pixel_size_mm=0.075, detector_distance_mm=200.0,
                         two_theta_deg=two_theta, psi_deg=0.0)
    expect = dx_px * 0.075 * math.cos(math.radians(two_theta)) ** 2 / 200.0
    assert got == pytest.approx(expect, rel=1e-12)


def test_pixel_to_angle_azimuthal_has_single_obliquity():
    two_theta, dx_px = 43.9778, 35.0
    got = pixel_to_angle(dx_px, pixel_size_mm=0.075, detector_distance_mm=200.0,
                         two_theta_deg=two_theta, psi_deg=90.0)
    expect = dx_px * 0.075 * math.cos(math.radians(two_theta)) / 200.0
    assert got == pytest.approx(expect, rel=1e-12)


@pytest.mark.parametrize('axis, radial, expected', [
    (35.0, 35.0,   0.0),
    (35.0, 125.0, 90.0),
    (10.0, 350.0, 20.0),
    (170.0, 10.0, 20.0),
])
def test_psi_from_geometry(axis, radial, expected):
    r = 100.0
    row = r * math.sin(math.radians(radial))
    col = r * math.cos(math.radians(radial))
    assert psi_from_geometry(row, col, 0.0, 0.0, axis) == pytest.approx(expected, abs=1e-6)


def test_dihedral_phi_round_trip():
    gamma = gamma_from_hkl(*HKL, GAN_A, GAN_C)
    G_mag = G_magnitude(*HKL, GAN_A, GAN_C)
    theta = theta_from_G(G_mag, LAM)
    for phi_deg in (0.0, 30.0, 45.0, 90.0, 135.0):
        G0_hat, z_lab, u_hat = build_canonical_frame(gamma, theta, math.radians(phi_deg))
        got = math.degrees(dihedral_phi(G_mag * G0_hat, z_lab, u_hat))
        assert got == pytest.approx(phi_deg, abs=1e-9)


# ── Comparison utility ───────────────────────────────────────────────────────

def test_compare_methods_runs_all_three():
    UB = _make_UB(0.0)
    peaks, crop_origin = _synthetic_pixel_peaks(LAMBDA_TRUE, UB)
    out = compare_methods(
        peaks, wavelength_angstrom=LAM, hkl=HKL, lattice=(GAN_A, GAN_C),
        detector=GEOM, UB=UB, crop_origin_px=crop_origin,
        phi_deg=0.0, satellite_axis_psi_deg=0.0, two_theta_0_deg=43.9778,
    )
    assert set(out) == {'monochromatic', 'laue_analytic', 'laue_forward'}
    for name, entry in out.items():
        assert entry['error'] is None, f'{name} failed: {entry["error"]}'
        assert np.isfinite(entry['period_nm'])

    # The routes read opposite components of the modulation; agreement would be
    # the surprise, not the disagreement.
    assert out['monochromatic']['period_nm'] != pytest.approx(
        out['laue_forward']['period_nm'], rel=1e-2)


def test_compare_methods_reports_errors_without_raising():
    """A partial comparison must still come back when a route cannot run."""
    out = compare_methods(
        MONO_REFERENCE_PEAKS, pixel_size_mm=0.075,
        detector_distance_mm=200.0, wavelength_angstrom=0.727,
    )
    assert out['monochromatic']['error'] is None
    assert out['laue_analytic']['error'] is not None
    assert out['laue_forward']['error'] is not None
    assert np.isnan(out['laue_forward']['period_nm'])


# ── §3.3 / §3.4 — validation against real data (AWAITING FIXTURE) ───────────
#
# These are the only genuinely independent checks of the geometry chain: every
# other test above is self-consistent by construction and cannot detect a wrong
# UB.  They need the real .det (with its UB_calib) plus one measured pattern.
# Fill REAL_DET_PATH and MEASURED_PARENT_PX to activate them.

REAL_DET_PATH = None          # path to the .det file
MEASURED_PARENT_PX = None     # (col, row) centroid of the indexed (105) spot
MEASURED_AXIS_DEG = -84.4     # from the manuscript segmentation
MEASURED_AXIS_FWHM = 1.48


@pytest.mark.skipif(REAL_DET_PATH is None,
                    reason='needs the real .det file — see REAL_DET_PATH')
def test_parent_peak_reprojection():
    """§3.3 — strongest validation: predicted parent position vs measured centroid.

    If this fails, the tilt convention or the UB is wrong, and no amount of
    correct satellite physics will rescue the projection.
    """
    geom, UB = DetectorGeometry.from_det_file(REAL_DET_PATH)
    G_lab, _ = lab_vectors_from_UB(HKL, (GAN_A, GAN_C), UB)
    col, row = direction_to_pixel(kf_hat(G_lab, LAB_KI), geom)
    meas_col, meas_row = MEASURED_PARENT_PX
    assert math.hypot(col - meas_col, row - meas_row) < 5.0


@pytest.mark.skipif(REAL_DET_PATH is None,
                    reason='needs the real .det file — see REAL_DET_PATH')
def test_predicted_satellite_axis_matches_measured():
    """§3.4 — the satellite axis is predicted from the crystal orientation alone.

    No free parameters enter: agreement supports the whole geometric picture,
    disagreement points at either the UB or the tilt convention.
    """
    geom, UB = DetectorGeometry.from_det_file(REAL_DET_PATH)
    G_lab, z_lab = lab_vectors_from_UB(HKL, (GAN_A, GAN_C), UB)
    predicted = predicted_satellite_axis_deg(
        G_lab, z_lab, LAMBDA_TRUE, [-3, -2, -1, 1, 2, 3], geom)
    delta = abs((predicted - MEASURED_AXIS_DEG + 90.0) % 180.0 - 90.0)
    assert delta < MEASURED_AXIS_FWHM


# ── The wrong UB frame, from the 15-MQW sample (2026-08-18) ──────────────────
#
# A real session lost a day to this: the UB went into `run_single_image` without
# `ub_from_beam_x_frame`, and the fit returned "20.00 nm" — the upper search
# bound — for every choice of detection parameter.  Everything else looked
# healthy, including a LaueTools simulation overlaying the measured image to
# 1.7 px, because |G| and γ are frame-independent and LaueTools was given the
# frame it expects.  Only the reprojection against the measured spot saw it.

MQW15_UB_RAW = np.array([
    [0.4251017712008649, -0.636576224442368,   -0.64347431541328],
    [0.8320650707370563,  0.5546771994737598,   0.0009604391109613625],
    [0.3563091385036692, -0.535820786139029,    0.7654671011611979]])
MQW15_GEOM = DetectorGeometry(dd=99.978, xcen=1079.92, ycen=983.47,
                              xbet=0.287, xgam=0.263, pixelsize=0.075,
                              framedim=(2162, 2068))
MQW15_CROP_ORIGIN = (1951, 562)
# order, pos_along_axis, amplitude, fwhm, sigma, crop_row, crop_col
MQW15_PEAKS_RAW = [
    (-3, -41.444887,    397.291294, 3.947455, 1.676344, 89.707954, 34.236301),
    (-2, -28.440462,   1078.911677, 2.796368, 1.187518, 77.562377, 38.883887),
    (-1, -16.106848,    997.486528, 2.093237, 0.888924, 66.043310, 43.291735),
    ( 0,  -0.100505, 854837.350356, 4.656196, 1.977321, 51.094071, 49.012160)]


def _mqw15_peaks():
    return [{'order': o, 'pos_along_axis': p, 'amplitude': a, 'fwhm': f,
             'sigma': s, 'position_2d': (r, c)}
            for o, p, a, f, s, r, c in MQW15_PEAKS_RAW]


def _mqw15_kwargs(UB):
    return dict(method='laue_forward', wavelength_angstrom=12.398 / 14.096,
                hkl=HKL, lattice=(GAN_A, GAN_C), detector=MQW15_GEOM, UB=UB,
                crop_origin_px=MQW15_CROP_ORIGIN)


def test_wrong_ub_frame_is_refused_rather_than_railed():
    """The frame error must abort, not come back as a period at the bound."""
    with pytest.raises(ValueError, match='ub_from_beam_x_frame'):
        layer_period_from_peaks(_mqw15_peaks(), **_mqw15_kwargs(MQW15_UB_RAW))


def test_wrong_ub_frame_is_refused_by_the_sl0_ladder_too():
    """Same guard on the other two consumers of the orientation."""
    for fn in (locate_sl0_from_ladder, check_order_assignment):
        with pytest.raises(ValueError, match='ub_from_beam_x_frame'):
            fn(_mqw15_peaks(), hkl=HKL, lattice=(GAN_A, GAN_C),
               UB=MQW15_UB_RAW, detector=MQW15_GEOM,
               crop_origin_px=MQW15_CROP_ORIGIN, period_angstrom=100.0)


def test_frame_converted_ub_recovers_the_period():
    """With the frame fixed the same peaks give a physical Λ and a tight fit."""
    res = layer_period_from_peaks(
        _mqw15_peaks(), **_mqw15_kwargs(ub_from_beam_x_frame(MQW15_UB_RAW)))
    assert not res['fit_at_bound']
    assert res['fit_success']
    assert res['period_nm'] == pytest.approx(10.011, abs=0.01)
    # The reprojection is what the raw frame failed by 20.7 deg.
    assert res['parent_offset_deg'] < 0.1
    assert res['fit_rms_deg'] * 1000 < 10.0


def test_wrong_frame_still_simulates_a_plausible_pattern():
    """Why the simulation overlay does not clear the frame: |G| and γ survive it.

    Pins the trap itself — the check that looked convincing and was blind.
    """
    raw   = lab_vectors_from_UB(HKL, (GAN_A, GAN_C), MQW15_UB_RAW)
    fixed = lab_vectors_from_UB(HKL, (GAN_A, GAN_C),
                                ub_from_beam_x_frame(MQW15_UB_RAW))
    assert np.linalg.norm(raw[0]) == pytest.approx(np.linalg.norm(fixed[0]), rel=1e-12)
    assert gamma_from_vectors(*raw) == pytest.approx(gamma_from_vectors(*fixed), rel=1e-12)


def test_diagnose_ub_frame_identifies_the_beam_x_case():
    """The diagnostic must point at one candidate, not merely rank them."""
    tt, chi = pixels_to_2theta_chi(611.012160, 2002.094071, MQW15_GEOM)
    frames = diagnose_ub_frame(MQW15_UB_RAW, HKL, (GAN_A, GAN_C),
                               float(tt[0]), float(chi[0]))
    assert frames['best'] == 'beam ∥ x → y'
    assert frames['beam ∥ x → y'] < 0.1
    # Every rival is either off the detector or tens of degrees away.
    for name, sep in frames.items():
        if name not in ('best', 'beam ∥ x → y'):
            assert sep > 10.0


def test_railed_fit_reports_its_bounds():
    """`fit_at_bound` alone cannot say which bound, so the range travels with it."""
    flipped = [dict(p, order=-p['order']) for p in _mled_peaks()]
    res = layer_period_from_peaks(flipped, method='laue_forward',
                                  wavelength_angstrom=0.7267, hkl=(1, 0, 5),
                                  lattice=MLED_LATTICE, detector=MLED_GEOM,
                                  UB=ub_from_beam_x_frame(UB_MLED_RAW),
                                  crop_origin_px=MLED_CROP_ORIGIN)
    assert res['fit_at_bound']
    assert not res['fit_success']
    lo, hi = res['period_bounds_angstrom']
    assert res['period_angstrom'] == pytest.approx(hi, rel=1e-6)
    assert (lo, hi) == (50.0, 200.0)


# ── Reporting: a failed fit must not read as a result ────────────────────────

def _summary_text(capsys, period):
    """Render `_print_summary` for a period dict and return what a user sees."""
    from laue.satellite.metrics import compute_metrics
    from laue.satellite.run_single_image import _print_summary

    peaks  = _mled_peaks()
    result = {'peaks': peaks, 'axis_angle': MLED_AXIS_DEG,
              'sl0_center': (float(MLED_BOX), float(MLED_BOX))}
    _print_summary(result, compute_metrics(peaks), period, sl0=None)
    return capsys.readouterr().out


def test_railed_fit_is_not_printed_as_a_period(capsys):
    """The bound must never appear on the 'Layer period' line as a value."""
    flipped = [dict(p, order=-p['order']) for p in _mled_peaks()]
    period = layer_period_from_peaks(flipped, method='laue_forward',
                                     wavelength_angstrom=0.7267, hkl=(1, 0, 5),
                                     lattice=MLED_LATTICE, detector=MLED_GEOM,
                                     UB=ub_from_beam_x_frame(UB_MLED_RAW),
                                     crop_origin_px=MLED_CROP_ORIGIN)
    out = _summary_text(capsys, period)
    assert 'NOT MEASURED' in out
    assert '20.00 nm' not in out
    assert '200.0 Å  =' not in out
    assert 'fit_rms' in out            # the diagnostics that explain it


def test_large_parent_offset_names_the_ub_frame(capsys):
    """The one number that identifies the frame error has to be impossible to miss."""
    period = {'period_angstrom': 100.0, 'period_nm': 10.0,
              'delta_q_inv_ang': 0.0628, 'per_pair': [], 'method': 'laue_forward',
              'fit_at_bound': False, 'fit_rms_deg': 0.005,
              'parent_offset_deg': 20.663, 'orders_used': [-3, -2, -1]}
    out = _summary_text(capsys, period)
    assert 'CHECK THE UB FRAME' in out
    assert 'ub_from_beam_x_frame' in out


def test_a_healthy_fit_prints_no_warning(capsys):
    """The warning must be a signal, not decoration on every run."""
    period = layer_period_from_peaks(
        _mqw15_peaks(), **_mqw15_kwargs(ub_from_beam_x_frame(MQW15_UB_RAW)))
    out = _summary_text(capsys, period)
    assert 'CHECK THE UB FRAME' not in out
    assert 'NOT MEASURED' not in out
    assert '10.01 nm' in out


# ── A period failure must not cost the figure ────────────────────────────────
#
# `run_single_image` is the bench for tuning segmentation, and the period is the
# step most likely to raise while the parameters are still wrong.  Losing the
# figure there leaves the caller adjusting parameters blind.

def _run_synthetic(**over):
    import matplotlib
    matplotlib.use('Agg')
    from laue.satellite.detection import make_synthetic_image
    from laue.satellite.run_single_image import run_single_image

    kw = dict(img_source=make_synthetic_image(n_satellites=3, spacing=22.0,
                                              axis_angle=35.0, envelope_decay=0.5,
                                              noise_level=50.0),
              boxsize=60, period_method='laue_forward', hkl=HKL,
              lattice=(GAN_A, GAN_C), UB=ub_from_beam_x_frame(MQW15_UB_RAW),
              detector=MQW15_GEOM, wavelength_angstrom=0.88,
              show_plot=False, quiet=True, print_summary=False)
    kw.update(over)
    return run_single_image(**kw)


def test_too_few_orders_still_returns_a_figure():
    res = _run_synthetic(n_range=(-1, 0))
    assert res['fig'] is not None
    assert res['period'] is None
    assert 'at least two non-zero satellite orders' in res['period_error']
    assert len(res['peaks_df']) == 2          # detection itself is untouched


def test_no_peaks_at_all_still_returns_a_figure():
    res = _run_synthetic(min_prominence=0.99)
    assert res['fig'] is not None
    assert res['period'] is None


def test_wrong_ub_frame_still_returns_a_figure_and_names_itself():
    """The guard must stop the number, not the picture."""
    res = _run_synthetic(UB=MQW15_UB_RAW)
    assert res['fig'] is not None
    assert res['period'] is None
    assert 'ub_from_beam_x_frame' in res['period_error']
    assert len(res['peaks_df']) == 7          # all orders still segmented


def test_period_error_is_none_on_success():
    """The field must mean 'it failed', not 'it was not asked for'."""
    res = _run_synthetic()
    assert res['period_error'] is None
    assert res['period'] is not None


# ── SL0 on a two-sided train (2026-08-19) ────────────────────────────────────
#
# Real case, S100, one reflection out of three: Λ came out healthy (10.81 nm)
# while SL0 was placed at -21.21 px, on top of SL-2 at -21.74.  Λ never uses SL0,
# so the period could not warn about it — the marker landing in an absurd place
# was the only symptom.  Cause: with satellites on BOTH sides of the parent the
# two innermost are -1 and +1, and inferring the step direction from their
# ordering inverts it, walking SL0 one order outward instead of inward.

S100_AXIS_DEG = -71.02
S100_CENTRE = (16.0, 42.0)
S100_LADDER = [(-3, -31.87), (-2, -21.74), (-1, -11.36),
               (0, +0.12), (1, +8.94), (2, +16.65)]


def _two_sided_peaks(ladder=S100_LADDER, axis_deg=S100_AXIS_DEG):
    rad = math.radians(axis_deg)
    cr, cc = S100_CENTRE
    return [{'order': n, 'pos_along_axis': s, 'amplitude': 1.0, 'fwhm': 2.0,
             'sigma': 0.85,
             'position_2d': (cr + s * math.sin(rad), cc + s * math.cos(rad))}
            for n, s in ladder]


def _two_sided_kwargs():
    return dict(hkl=HKL, lattice=(GAN_A, GAN_C),
                UB=ub_from_beam_x_frame(MQW15_UB_RAW), detector=MQW15_GEOM,
                crop_origin_px=(1905, 572), period_angstrom=108.1)


def test_sl0_on_a_two_sided_train_lands_near_the_parent():
    res = locate_sl0_from_ladder(_two_sided_peaks(), **_two_sided_kwargs())
    sl0 = res['sl0_pos_along_axis']
    # Within one step of the parent at +0.12, not one step the other way.
    assert abs(sl0 - 0.12) < res['gap_pred_px']
    # And nowhere near SL-2, which is where the inverted step used to put it.
    assert abs(sl0 - (-21.74)) > 10.0


def test_extra_positive_orders_do_not_move_sl0():
    """Adding satellites on the far side must not change the prediction."""
    kw = _two_sided_kwargs()
    both = locate_sl0_from_ladder(_two_sided_peaks(), **kw)
    neg  = locate_sl0_from_ladder(
        [p for p in _two_sided_peaks() if p['order'] <= 0], **kw)
    assert both['sl0_pos_along_axis'] == pytest.approx(
        neg['sl0_pos_along_axis'], abs=1e-9)


def test_sl0_scale_pair_stays_on_one_side():
    """The local scale must not use a baseline that straddles the parent."""
    res = locate_sl0_from_ladder(_two_sided_peaks(), **_two_sided_kwargs())
    # -1 -> -2 is 10.38 px; -1 -> +1 would be 20.30 px and cross the bulk.
    assert res['gap_meas_px'] == pytest.approx(10.38, abs=0.01)


def test_sl0_direction_survives_a_reversed_train():
    """Position may increase or decrease with order; only the trend decides."""
    mirrored = [(n, -s) for n, s in S100_LADDER]
    res = locate_sl0_from_ladder(_two_sided_peaks(ladder=mirrored),
                                 **_two_sided_kwargs())
    assert abs(res['sl0_pos_along_axis'] - (-0.12)) < res['gap_pred_px']
    assert abs(res['sl0_pos_along_axis'] - (+21.74)) > 10.0


# ── Order-label sign resolved against the model (§4.11.2) ────────────────────
#
# Detection's +n is a detector-space convention with no crystallographic
# reference, so it is inverted for some reflections.  The period announces it by
# railing against a bound; the asymmetry indicators would not — they would simply
# come out with the opposite sign.

def _sign_kwargs():
    return dict(hkl=HKL, lattice=MLED_LATTICE,
                UB=ub_from_beam_x_frame(UB_MLED_RAW), detector=MLED_GEOM,
                crop_origin_px=MLED_CROP_ORIGIN)


def test_correct_labels_are_left_alone():
    res = resolve_order_sign(_mled_peaks(), **_sign_kwargs())
    assert res['confident']
    assert not res['inverted']
    assert res['arrow_cos'] > 0.99


def test_inverted_labels_are_detected():
    flipped = [dict(p, order=-p['order']) for p in _mled_peaks()]
    res = resolve_order_sign(flipped, **_sign_kwargs())
    assert res['confident']
    assert res['inverted']
    assert res['arrow_cos'] < -0.99


def test_correction_makes_the_two_labellings_agree():
    """The point of the fix: the same image gives the same Λ either way."""
    kw = _sign_kwargs()
    flipped = [dict(p, order=-p['order']) for p in _mled_peaks()]
    a, _ = resolve_and_apply_order_sign(_mled_peaks(), **kw)
    b, _ = resolve_and_apply_order_sign(flipped, **kw)
    assert sorted(p['order'] for p in a) == sorted(p['order'] for p in b)
    p_a = layer_period_from_peaks(a, method='laue_forward',
                                  wavelength_angstrom=0.7267, **kw)
    p_b = layer_period_from_peaks(b, method='laue_forward',
                                  wavelength_angstrom=0.7267, **kw)
    assert p_a['period_nm'] == pytest.approx(p_b['period_nm'], rel=1e-12)
    assert not p_a['fit_at_bound'] and not p_b['fit_at_bound']


def test_signed_metrics_follow_the_correction():
    """Why the fix lives above the metrics rather than inside the period route.

    `delta_q` is signed, and so are the asymmetry indicators when both sides are
    present.  An inverted label set flips them with no warning of any kind — the
    period at least announces itself by railing against a bound.
    """
    from laue.satellite.metrics import compute_metrics
    kw = _sign_kwargs()
    flipped = [dict(p, order=-p['order']) for p in _mled_peaks()]

    truth = compute_metrics(_mled_peaks())
    raw   = compute_metrics(flipped)
    fixed = compute_metrics(resolve_and_apply_order_sign(flipped, **kw)[0])

    assert raw['delta_q'] == pytest.approx(-truth['delta_q'])    # silent flip
    for key in ('delta_q', 'n_sat', 'bulk_pos', 'alpha'):
        assert fixed[key] == pytest.approx(truth[key])           # correction undoes it


def test_a_wrong_ub_frame_refuses_to_decide_the_sign():
    """Gate 1: an orientation that does not point here has no authority."""
    kw = _sign_kwargs()
    kw['UB'] = UB_MLED_RAW.T            # a plausible-looking but wrong frame
    res = resolve_order_sign(_mled_peaks(), **kw)
    assert not res['confident']
    assert not res['inverted']
    assert 'parent_offset' in res['reason']


def test_a_train_off_the_predicted_line_refuses_to_decide_the_sign():
    """Gate 2: with the line wrong, the arrow question does not apply."""
    peaks = _mled_peaks()
    parent = next(p for p in peaks if p['order'] == 0)
    pr, pc = parent['position_2d']
    t = math.radians(40.0)
    rotated = []
    for p in peaks:                      # rotate the satellites about the parent
        if p['order'] == 0:
            rotated.append(p)
            continue
        dr, dc = p['position_2d'][0] - pr, p['position_2d'][1] - pc
        rotated.append(dict(p, position_2d=(
            pr + dr * math.cos(t) - dc * math.sin(t),
            pc + dr * math.sin(t) + dc * math.cos(t))))
    res = resolve_order_sign(rotated, **_sign_kwargs())
    assert res['parent_offset_deg'] < 1.0      # gate 1 still passes
    assert not res['confident']
    assert 'train_delta' in res['reason']


def test_sign_resolution_needs_the_parent_peak():
    """No order-0 peak means no way to check the reflection, so no verdict."""
    res = resolve_order_sign([p for p in _mled_peaks() if p['order'] != 0],
                             **_sign_kwargs())
    assert not res['confident']
    assert not res['inverted']


def test_run_single_image_reports_the_order_sign():
    """Wiring: the verdict must reach the caller, not stay inside the period."""
    res = _run_synthetic()
    assert 'order_sign' in res
    assert res['order_sign'] is not None
    assert set(res['order_sign']) >= {'inverted', 'confident', 'reason'}


def test_a_correction_is_never_silent(capsys):
    """Relabelling changes what every signed quantity means — it must be printed."""
    from laue.satellite.run_single_image import _print_summary
    from laue.satellite.metrics import compute_metrics

    peaks  = _mled_peaks()
    result = {'peaks': peaks, 'axis_angle': MLED_AXIS_DEG,
              'sl0_center': (float(MLED_BOX), float(MLED_BOX))}
    _print_summary(result, compute_metrics(peaks), None, sl0=None,
                   order_sign={'inverted': True, 'confident': True,
                               'arrow_cos': -0.999, 'reason': ''})
    out = capsys.readouterr().out
    assert 'INVERTED' in out
    assert 'arrow_cos' in out


# ── interactive_map serves both period routes (2026-08-19) ───────────────────

def _viz_kwargs(**over):
    kw = dict(period_method='monochromatic', pixel_size_mm=None,
              detector_distance_mm=None, wavelength_angstrom=None, energy_kev=None,
              two_theta_0_deg=0.0, chi_deg=0.0, hkl=None, lattice=None, UB=None,
              detector=None, sl0_boxsize=3.0)
    kw.update(over)
    return kw


def test_interactive_map_forwards_the_laue_route():
    from laue.satellite.visualize import _period_kwargs
    kw = _period_kwargs(**_viz_kwargs(
        period_method='laue_forward', hkl=HKL, lattice=MLED_LATTICE,
        UB=ub_from_beam_x_frame(UB_MLED_RAW), detector=MLED_GEOM,
        wavelength_angstrom=0.7267))
    assert kw['period_method'] == 'laue_forward'
    assert kw['hkl'] == HKL and kw['detector'] is MLED_GEOM
    assert 'pixel_size_mm' not in kw          # never mix the two routes


def test_interactive_map_forwards_the_monochromatic_route():
    from laue.satellite.visualize import _period_kwargs
    kw = _period_kwargs(**_viz_kwargs(
        pixel_size_mm=0.075, detector_distance_mm=70.0, wavelength_angstrom=0.7267))
    assert kw['pixel_size_mm'] == 0.075
    assert 'hkl' not in kw
    assert 'period_method' not in kw           # run_single_image's own default


def test_interactive_map_without_geometry_shows_detection_only():
    from laue.satellite.visualize import _period_kwargs
    assert _period_kwargs(**_viz_kwargs()) == {}


def test_interactive_map_refuses_an_incomplete_laue_set():
    """Falling back would put two different quantities side by side in silence."""
    from laue.satellite.visualize import _period_kwargs
    with pytest.raises(ValueError, match='detector'):
        _period_kwargs(**_viz_kwargs(period_method='laue_forward', hkl=HKL,
                                     lattice=MLED_LATTICE,
                                     UB=ub_from_beam_x_frame(UB_MLED_RAW)))


def test_interactive_map_prefers_the_laue_route_when_both_are_given():
    """Same precedence as run_single_image, or the panel would not match the map."""
    from laue.satellite.visualize import _period_kwargs
    kw = _period_kwargs(**_viz_kwargs(
        period_method='laue_forward', hkl=HKL, lattice=MLED_LATTICE,
        UB=ub_from_beam_x_frame(UB_MLED_RAW), detector=MLED_GEOM,
        wavelength_angstrom=0.7267, pixel_size_mm=0.075, detector_distance_mm=70.0))
    assert 'hkl' in kw and 'pixel_size_mm' not in kw


def test_laue_only_columns_are_labelled_on_the_map():
    """Every column the Laue batch emits should be selectable with a real label."""
    from laue.satellite.visualize import _METRIC_LABELS
    for col in ('period_nm', 'fit_rms_deg', 'parent_offset_deg', 'train_delta_deg',
                'gamma_deg', 'sl0_confirmed', 'bulk_sl0_offset_px',
                'order_sign_inverted', 'order_sign_arrow_cos'):
        assert col in _METRIC_LABELS
        assert _METRIC_LABELS[col] != col


def test_interactive_map_runs_on_both_routes(recwarn):
    """End to end, headless: the map builds and neither route raises."""
    import matplotlib
    matplotlib.use('Agg')
    import pandas as pd
    from laue.satellite.visualize import interactive_map

    n = 3
    df = pd.DataFrame([{'i': i, 'j': j, 'frame_idx': i * n + j, 'x_um': float(i),
                        'y_um': float(j), 'status': 'ok', 'period_nm': 10.0 + 0.1 * i,
                        'fit_rms_deg': 0.005}
                       for i in range(n) for j in range(n)])
    common = dict(img_source='unread.h5', roi_center=(100, 100), boxsize=20,
                  metric='period_nm')
    interactive_map(df, **common, period_method='laue_forward', hkl=HKL,
                    lattice=MLED_LATTICE, UB=ub_from_beam_x_frame(UB_MLED_RAW),
                    detector=MLED_GEOM, wavelength_angstrom=0.7267)
    interactive_map(df, **common, pixel_size_mm=0.075,
                    detector_distance_mm=70.0, wavelength_angstrom=0.7267)
    interactive_map(df, **common)


# ── Which image the profile panel shows (2026-08-19) ─────────────────────────

def test_profile_panel_defaults_to_the_subtracted_image():
    """The detection works on the subtracted crop, so the panel should show it."""
    res = _run_synthetic()
    titles = [a.get_title() for a in res['fig'].axes
              if a.get_title().startswith('Profile')]
    assert titles
    assert all('background-subtracted' in t for t in titles)


def test_profile_panel_can_still_show_measured_counts():
    res = _run_synthetic(profile_source='raw')
    titles = [a.get_title() for a in res['fig'].axes
              if a.get_title().startswith('Profile')]
    assert titles
    assert all('raw' in t for t in titles)


def test_the_two_profile_sources_differ():
    """A bright parent's tail is exactly what the subtraction removes."""
    sub = _run_synthetic()
    raw = _run_synthetic(profile_source='raw')

    def _curve(res):
        ax = next(a for a in res['fig'].axes if a.get_title().startswith('Profile'))
        return ax.lines[0].get_ydata()

    assert not np.allclose(_curve(sub), _curve(raw))


def test_an_unknown_profile_source_is_refused():
    with pytest.raises(ValueError, match='profile_source'):
        _run_synthetic(profile_source='background')
